#!/usr/bin/env bash
# Birkin — one-command install
# Usage: curl -fsSL https://raw.githubusercontent.com/NickAiNYC/Birkin/main/install.sh | bash
set -euo pipefail

BIRKIN_DIR="${BIRKIN_DIR:-$HOME/.birkin}"
REPO="https://github.com/NickAiNYC/Birkin"

echo ""
echo "  ╔══════════════════════════════════╗"
echo "  ║  Birkin — iPhone Agent Controller ║"
echo "  ╚══════════════════════════════════╝"
echo ""

# ── Prereqs ────────────────────────────────────────────────────────────────
check_prereq() {
    if ! command -v "$1" &>/dev/null; then
        echo "❌ Required: $1 is not installed."
        echo "   Install it then re-run this script."
        exit 1
    fi
}
check_prereq git
check_prereq docker

if ! docker compose version &>/dev/null 2>&1; then
    echo "❌ Docker Compose v2 required. Update Docker Desktop and retry."
    exit 1
fi

# ── Clone ──────────────────────────────────────────────────────────────────
if [ -d "$BIRKIN_DIR/.git" ]; then
    echo "↻  Updating existing install at $BIRKIN_DIR"
    git -C "$BIRKIN_DIR" pull --ff-only
else
    echo "⬇  Cloning Birkin to $BIRKIN_DIR"
    git clone "$REPO" "$BIRKIN_DIR"
fi

cd "$BIRKIN_DIR"

# ── .env ───────────────────────────────────────────────────────────────────
if [ ! -f .env ]; then
    echo ""
    echo "📝  Creating .env — edit it after install to set push notification keys"
    BIRKIN_TOKEN="$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"
    WEBUI_SECRET="$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"
    cat > .env <<ENV
# Auto-generated by install.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Required: used by Siri Shortcuts + all API calls
BIRKIN_TOKEN=${BIRKIN_TOKEN}

# Required: Open WebUI session secret
WEBUI_SECRET_KEY=${WEBUI_SECRET}

# Optional: monthly budget cap in USD (triggers push alert when exceeded)
BIRKIN_BUDGET_USD=50

# Optional: port Birkin listens on (default 3000)
BIRKIN_PORT=3000

# Optional: push notifications — fill ONE provider
# Pusher Beams:
# PUSHER_INSTANCE_ID=
# PUSHER_SECRET_KEY=
# OneSignal:
# ONESIGNAL_APP_ID=
# ONESIGNAL_API_KEY=

# Optional: disable new user signup in Open WebUI (recommended)
ENABLE_SIGNUP=false
ENV
    echo ""
    echo "  ✅  .env created with auto-generated tokens"
fi

# ── Start ──────────────────────────────────────────────────────────────────
echo ""
echo "🚀  Starting Birkin..."
docker compose up -d --build

# ── Wait for health ────────────────────────────────────────────────────────
echo -n "   Waiting for API"
for i in $(seq 1 30); do
    if curl -sf "http://localhost:${BIRKIN_PORT:-3000}/health" &>/dev/null; then
        echo " ✅"
        break
    fi
    echo -n "."
    sleep 2
done

# ── Done ───────────────────────────────────────────────────────────────────
LOCAL_IP=$(ipconfig getifaddr en0 2>/dev/null || hostname -I 2>/dev/null | awk '{print $1}' || echo "your-local-ip")
echo ""
echo "  ══════════════════════════════════════════"
echo "  Birkin is running!"
echo ""
echo "  Open WebUI (chat):    http://${LOCAL_IP}:${BIRKIN_PORT:-3000}"
echo "  API health:           http://${LOCAL_IP}:${BIRKIN_PORT:-3000}/health"
echo "  API docs:             http://${LOCAL_IP}:${BIRKIN_PORT:-3000}/docs"
echo ""
echo "  📱  Add to iPhone Home Screen:"
echo "      Safari → http://${LOCAL_IP}:${BIRKIN_PORT:-3000}"
echo "      Share → Add to Home Screen → name it 'Birkin'"
echo ""
echo "  🗣  Siri Shortcut trigger:"
echo "      POST http://${LOCAL_IP}:${BIRKIN_PORT:-3000}/api/skills/{name}/trigger"
echo "      Authorization: Bearer \$(grep BIRKIN_TOKEN .env | cut -d= -f2)"
echo ""
echo "  Your BIRKIN_TOKEN:"
grep BIRKIN_TOKEN .env | cut -d= -f2
echo ""
echo "  ══════════════════════════════════════════"
