/**
 * Retry policy for the Directora Brief API sign-off path.
 *
 * Aligned with `HANDOFF.md` §7c (retry table). The hard rules:
 *
 *   * Retry only on 503, 429, and network timeouts.
 *   * Reuse the SAME `Idempotency-Key` across retries of the same
 *     attempt — Directora returns the byte-identical replay with
 *     `X-Idempotency-Replayed: true`.
 *   * Never retry on 401, 403, 404, 409, 422. Those are authoritative.
 *   * Honour `Retry-After`; fall back to exponential backoff (250ms, 1s, 4s).
 *
 * Exposes a single helper, `signBriefWithRetry`, that wraps the
 * existing `BriefClient.signBrief` and applies the policy. Callers
 * never need to think about the rules.
 */
import {
  BriefApiError,
  BriefClient,
} from "./briefClient";
import type {
  SignBriefResponse,
  SignatureBlock,
  ClientBlock,
} from "../types/contract";

/**
 * HTTP statuses we retry. `429` reserved for future rate-limiting on
 * Directora; the engine doesn't emit it today but the client should
 * tolerate it.
 */
export const RETRYABLE_STATUSES: ReadonlySet<number> = new Set([503, 429]);

/**
 * Error codes we retry as a soft signal. Conservative — only the
 * generic engine_or_ledger_failure bucket, since 5xx in our taxonomy
 * means "transient inside Directora".
 *
 * If you do not want the soft retry path, set `retryOnSoftErrors: false`.
 */
export const RETRYABLE_ERROR_CODES: ReadonlySet<string> = new Set([
  "engine_or_ledger_failure",
]);

/**
 * Statuses that MUST NOT be retried, no matter what.
 */
export const NEVER_RETRY_STATUSES: ReadonlySet<number> = new Set([
  400, 401, 403, 404, 409, 422,
]);

/**
 * Default backoff schedule in milliseconds, applied when the server
 * does NOT send a `Retry-After` header. Indexed by retry attempt:
 *     attempt 2 → BACKOFF_SCHEDULE_MS[0]   (250 ms)
 *     attempt 3 → BACKOFF_SCHEDULE_MS[1]   (500 ms)
 *     attempt 4 → BACKOFF_SCHEDULE_MS[2]   (1000 ms)
 * Beyond the schedule the last entry is reused.
 *
 * Jittered by ±15 % at call time so concurrent clients don't fall
 * into lockstep retry storms.
 */
export const BACKOFF_SCHEDULE_MS: readonly number[] = [250, 500, 1000];

/** ±15 % jitter applied to every scheduled backoff. */
export const BACKOFF_JITTER_PCT = 0.15;

export interface SignWithRetryOptions {
  briefId: string;
  providerId: string;
  signature: SignatureBlock;
  client: ClientBlock;
  /**
   * Full Idempotency-Key value. Generated by the store layer once per
   * intent-to-sign and reused across every retry of that attempt.
   * See `src/api/idempotencyStore.ts`.
   */
  idempotencyKey: string;
  /** Optional engine-context echo so Directora can detect stale signs. */
  engineRunId?: string;
  authorityBriefVersion?: string;
  providerBriefVersion?: string;
  /**
   * Maximum number of retries beyond the initial attempt. Default `3`,
   * matching `BACKOFF_SCHEDULE_MS`. `0` disables retry.
   */
  maxRetries?: number;
  /**
   * Override the default backoff schedule. Default
   * `BACKOFF_SCHEDULE_MS` (`[250, 500, 1000]`). Each entry is jittered
   * by ±15 % independently.
   */
  backoffScheduleMs?: readonly number[];
  /** Jitter band (e.g. `0.15` for ±15 %). Default `BACKOFF_JITTER_PCT`. */
  jitterPct?: number;
  /** Allow soft retry on engine_or_ledger_failure. Defaults to true. */
  retryOnSoftErrors?: boolean;
  /** Hook fired on every attempt (success, retry, or terminal). */
  onAttempt?: (info: RetryAttemptInfo) => void;
  /** Reserved for future timeout integration; ignored today. */
  requestTimeoutMs?: number;
}

export interface RetryAttemptInfo {
  attempt: number;          // 1-indexed
  totalAttempts: number;    // attempt budget including the first try
  outcome: "success" | "retry" | "give_up";
  status?: number;
  errorCode?: string;
  requestId?: string | null;
  retryAfterMs?: number;
  /** Replayed by the server (idempotent same-key, same-body)? */
  replayed?: boolean;
}

export class MaxRetriesExceededError extends Error {
  attempts: number;
  /**
   * `X-Request-ID` of the final failed attempt (when available). Quote
   * this in support tickets — it's the engine-side correlation id.
   */
  requestId: string | null;
  lastError?: BriefApiError | unknown;
  constructor(
    attempts: number,
    lastError?: BriefApiError | unknown,
    requestId: string | null = null,
  ) {
    super(`Signing failed after ${attempts} attempts`);
    this.attempts = attempts;
    this.lastError = lastError;
    this.requestId = requestId;
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Apply ±jitter to a scheduled delay so concurrent clients don't fire
 * in lockstep. Floor at 0 ms.
 */
export function applyJitter(ms: number, jitterPct: number): number {
  if (jitterPct <= 0) return Math.max(0, Math.floor(ms));
  const delta = ms * jitterPct;
  const jitter = (Math.random() * 2 - 1) * delta;
  return Math.max(0, Math.floor(ms + jitter));
}

/**
 * Pick the scheduled backoff for the given retry attempt.
 *
 * `attempt` is 1-indexed for the FAILED attempt that's about to be
 * retried (so `attempt=1` returns the wait BEFORE attempt 2).
 */
export function scheduledBackoffMs(
  attempt: number,
  schedule: readonly number[],
  jitterPct: number,
): number {
  const idx = Math.min(attempt - 1, schedule.length - 1);
  const base = schedule[Math.max(0, idx)] ?? 250;
  return applyJitter(base, jitterPct);
}

/**
 * Sign a brief with the canonical retry policy.
 *
 * Throws:
 *   * BriefApiError              for any non-retryable error
 *   * MaxRetriesExceededError    after exhausting retries
 */
export async function signBriefWithRetry(
  client: BriefClient,
  opts: SignWithRetryOptions,
): Promise<SignBriefResponse> {
  const maxRetries = opts.maxRetries ?? 3;
  const schedule = opts.backoffScheduleMs ?? BACKOFF_SCHEDULE_MS;
  const jitterPct = opts.jitterPct ?? BACKOFF_JITTER_PCT;
  const retryOnSoft = opts.retryOnSoftErrors ?? true;
  const totalAttempts = maxRetries + 1;

  let lastErr: BriefApiError | unknown = undefined;
  let lastRequestId: string | null = null;

  const computeDelay = (
    attempt: number,
    retryAfterSeconds: number | null | undefined,
  ): number => {
    if (typeof retryAfterSeconds === "number") {
      // Honour Retry-After verbatim; still apply jitter so concurrent
      // clients don't all wake at the same millisecond.
      return applyJitter(retryAfterSeconds * 1000, jitterPct);
    }
    return scheduledBackoffMs(attempt, schedule, jitterPct);
  };

  for (let attempt = 1; attempt <= totalAttempts; attempt++) {
    try {
      const response = await client.signBrief({
        briefId: opts.briefId,
        providerId: opts.providerId,
        signature: opts.signature,
        client: opts.client,
        idempotencyKey: opts.idempotencyKey,
        engineRunId: opts.engineRunId,
        authorityBriefVersion: opts.authorityBriefVersion,
        providerBriefVersion: opts.providerBriefVersion,
      });
      opts.onAttempt?.({
        attempt,
        totalAttempts,
        outcome: "success",
        status: 200,
      });
      return response;
    } catch (raw) {
      lastErr = raw;
      if (raw instanceof BriefApiError) {
        lastRequestId = raw.requestId;
        // Authoritative — never retry.
        if (NEVER_RETRY_STATUSES.has(raw.status)) {
          opts.onAttempt?.({
            attempt,
            totalAttempts,
            outcome: "give_up",
            status: raw.status,
            errorCode: String(raw.code),
            requestId: raw.requestId,
          });
          throw raw;
        }
        // Retryable HTTP status (503/429).
        if (RETRYABLE_STATUSES.has(raw.status)) {
          if (attempt >= totalAttempts) break;
          const retryAfterMs = computeDelay(attempt, raw.retryAfterSeconds);
          opts.onAttempt?.({
            attempt,
            totalAttempts,
            outcome: "retry",
            status: raw.status,
            errorCode: String(raw.code),
            requestId: raw.requestId,
            retryAfterMs,
          });
          await sleep(retryAfterMs);
          continue;
        }
        // Soft retry on engine_or_ledger_failure (5xx bucket).
        if (
          retryOnSoft &&
          RETRYABLE_ERROR_CODES.has(String(raw.code)) &&
          attempt < totalAttempts
        ) {
          const ms = computeDelay(attempt, null);
          opts.onAttempt?.({
            attempt,
            totalAttempts,
            outcome: "retry",
            status: raw.status,
            errorCode: String(raw.code),
            requestId: raw.requestId,
            retryAfterMs: ms,
          });
          await sleep(ms);
          continue;
        }
        // Anything else surfaces immediately.
        opts.onAttempt?.({
          attempt,
          totalAttempts,
          outcome: "give_up",
          status: raw.status,
          errorCode: String(raw.code),
          requestId: raw.requestId,
        });
        throw raw;
      }
      // Network-level failure (fetch threw): treat as transient.
      if (attempt < totalAttempts) {
        const ms = computeDelay(attempt, null);
        opts.onAttempt?.({
          attempt,
          totalAttempts,
          outcome: "retry",
          status: undefined,
          errorCode: "network_error",
          retryAfterMs: ms,
        });
        await sleep(ms);
        continue;
      }
      opts.onAttempt?.({
        attempt,
        totalAttempts,
        outcome: "give_up",
        status: undefined,
        errorCode: "network_error",
      });
      throw new MaxRetriesExceededError(totalAttempts, raw, lastRequestId);
    }
  }

  throw new MaxRetriesExceededError(totalAttempts, lastErr, lastRequestId);
}
